zle_highlight=(region:bg=#4c3743 special:fg=#414b50 suffix:fg=#414b50 isearch:italic paste:none)

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
ZSH_HIGHLIGHT_STYLES[cursor-matchingbracket]='bg=#495156'
ZSH_HIGHLIGHT_STYLES[bracket-error]='fg=#dbbc7f'
ZSH_HIGHLIGHT_STYLES[bracket-level-1]=''
ZSH_HIGHLIGHT_STYLES[bracket-level-2]=''
ZSH_HIGHLIGHT_STYLES[bracket-level-3]=''
ZSH_HIGHLIGHT_STYLES[bracket-level-4]=''
ZSH_HIGHLIGHT_STYLES[bracket-level-5]=''

ZSH_HIGHLIGHT_STYLES[default]='none'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=#e67e80'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=#e67e80'
ZSH_HIGHLIGHT_STYLES[alias]='fg=#a7c080'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg=#a7c080'
ZSH_HIGHLIGHT_STYLES[global-alias]='fg=#a7c080'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=#a7c080'
ZSH_HIGHLIGHT_STYLES[function]='fg=#a7c080'
ZSH_HIGHLIGHT_STYLES[command]='fg=#a7c080'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=#e67e80'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=#859289'
ZSH_HIGHLIGHT_STYLES[autodirectory]='fg=#83c092'
ZSH_HIGHLIGHT_STYLES[path]='fg=#83c092'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=#e69875'
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg=#e69875'
ZSH_HIGHLIGHT_STYLES[command-substitution]='fg=#e69875'
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter]='fg=#e69875'
ZSH_HIGHLIGHT_STYLES[process-substitution]='fg=#e69875'
ZSH_HIGHLIGHT_STYLES[process-substitution-delimiter]='fg=#e69875'
ZSH_HIGHLIGHT_STYLES[arithmetic-expansion]='fg=#e69875'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='none'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='none'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg=#d3c6aa'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument-delimiter]='fg=#d3c6aa'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#d3c6aa'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#d3c6aa'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#d3c6aa'
ZSH_HIGHLIGHT_STYLES[rc-quote]='fg=#e67e80'
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg=#d3c6aa'
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]='fg=#d3c6aa'
ZSH_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='fg=#d3c6aa'
ZSH_HIGHLIGHT_STYLES[assign]='none'
ZSH_HIGHLIGHT_STYLES[redirection]='fg=#859289'
ZSH_HIGHLIGHT_STYLES[comment]='fg=#859289'
ZSH_HIGHLIGHT_STYLES[named-fd]='fg=#a7c080'
ZSH_HIGHLIGHT_STYLES[numeric-fd]='fg=#a7c080'
ZSH_HIGHLIGHT_STYLES[arg0]='fg=#d3c6aa'
