zle_highlight=(region:bg=#434c5e special:fg=#6c6f75 suffix:fg=#6c6f75 isearch:italic paste:none)

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
ZSH_HIGHLIGHT_STYLES[cursor-matchingbracket]='bg=#6c6f75'
ZSH_HIGHLIGHT_STYLES[bracket-error]='fg=#ebcb8b'
ZSH_HIGHLIGHT_STYLES[bracket-level-1]=''
ZSH_HIGHLIGHT_STYLES[bracket-level-2]=''
ZSH_HIGHLIGHT_STYLES[bracket-level-3]=''
ZSH_HIGHLIGHT_STYLES[bracket-level-4]=''
ZSH_HIGHLIGHT_STYLES[bracket-level-5]=''

ZSH_HIGHLIGHT_STYLES[default]='none'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=#bf616a'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=#5e81ac'
ZSH_HIGHLIGHT_STYLES[alias]='fg=#88c0d0'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg=#88c0d0'
ZSH_HIGHLIGHT_STYLES[global-alias]='fg=#88c0d0'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=#88c0d0'
ZSH_HIGHLIGHT_STYLES[function]='fg=#88c0d0'
ZSH_HIGHLIGHT_STYLES[command]='fg=#88c0d0'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=#5e81ac'
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=#aab0ba'
ZSH_HIGHLIGHT_STYLES[autodirectory]='fg=#a093c7'
ZSH_HIGHLIGHT_STYLES[path]='fg=#a093c7'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=#8fbcbb'
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg=#8fbcbb'
ZSH_HIGHLIGHT_STYLES[command-substitution]='fg=#8fbcbb'
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter]='fg=#8fbcbb'
ZSH_HIGHLIGHT_STYLES[process-substitution]='fg=#8fbcbb'
ZSH_HIGHLIGHT_STYLES[process-substitution-delimiter]='fg=#8fbcbb'
ZSH_HIGHLIGHT_STYLES[arithmetic-expansion]='fg=#8fbcbb'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='none'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='none'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg=#8fbcbb'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument-delimiter]='fg=#8fbcbb'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#81a1c1'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#81a1c1'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#81a1c1'
ZSH_HIGHLIGHT_STYLES[rc-quote]='fg=#81a1c1'
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg=#8fbcbb'
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]='fg=#8fbcbb'
ZSH_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='fg=#8fbcbb'
ZSH_HIGHLIGHT_STYLES[assign]='none'
ZSH_HIGHLIGHT_STYLES[redirection]='fg=#aab0ba'
ZSH_HIGHLIGHT_STYLES[comment]='fg=#aab0ba'
ZSH_HIGHLIGHT_STYLES[named-fd]='fg=#a3be8c'
ZSH_HIGHLIGHT_STYLES[numeric-fd]='fg=#a3be8c'
ZSH_HIGHLIGHT_STYLES[arg0]='fg=#88c0d0'
