gui:
    theme:
        selectedLineBgColor:
            - '#414b50' # set to `default` to have no background colour
            - bold
os:
    editPreset: 'nvim'
git:
    autoFetch: false
    autoForwardBranches: 'allBranches'
promptToReturnFromSubprocess: false
keybinding:
    universal:
        quit: <disabled>
    main:
        toggleSelectHunk: 'V'
        toggleDragSelect-alt: <disabled>
