gui:
  theme:
    selectedLineBgColor:
      - black # set to `default` to have no background colour
      - bold
    selectedRangeBgColor:
      - black
      - bold
os:
  editPreset: 'nvim'
git:
  autoFetch: false
promptToReturnFromSubprocess: false
quitOnTopLevelReturn: true
keybinding:
  universal:
    quit: null
  main:
    toggleSelectHunk: 'V'
    toggleDragSelect-alt: null
