gui:
  theme:
    selectedLineBgColor:
      - '#414b50' # set to `default` to have no background colour
      - bold
os:
  editPreset: 'nvim'
git:
  autoFetch: false
promptToReturnFromSubprocess: false
keybinding:
  universal:
    quit: null
  main:
    toggleSelectHunk: 'V'
    toggleDragSelect-alt: null
