[mgr]
prepend_keymap = [
	{ on = "M", run = "plugin mount" },
	{ on = "l", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
]
append_keymap = [
	{ on = [ "<C-c>" ], run = "close", desc = "Close the current tab, or quit if it is last tab" },

	# Operation
	{ on = [ "g", "." ], run = "hidden toggle", desc = "Toggle the visibility of hidden files" },

	# Help
	{ on = [ "g", "?" ], run = "help", desc = "Open help" },
]

[select]
append_keymap = [
	{ on = [ "g", "?" ], run = "help", desc = "Open help" }
]

[input]
append_keymap = [
	{ on = [ "<C-c>" ], run = "close", desc = "Cancel input" },
	{ on = [ "g", "?" ], run = "help", desc = "Open help" }
]

[completion]
append_keymap = [
	{ on = [ "<C-c>" ], run = "close", desc = "Cancel completion" },
	{ on = [ "g", "?" ], run = "help", desc = "Open help" }
]
