vim.api.nvim_create_augroup("nvim-lightbulb-update", {})
vim.api.nvim_create_autocmd("CursorHold", {group = "nvim-lightbulb-update", callback = function()
	require("nvim-lightbulb").update_lightbulb({sign = {enabled = false}, status_text = {enabled = true}})
end})

local c = require("nord.colours")
vim.api.nvim_create_augroup("nvim-lightbulb-hl", {})
vim.api.nvim_create_autocmd("ColorScheme", {group = "nvim-lightbulb-hl", pattern = "nord", callback = function()
	vim.api.nvim_set_hl(0, "LightBulbFloatWin", {bg = c.bg})
end})
vim.api.nvim_exec_autocmds("ColorScheme", {group = "nvim-lightbulb-hl", pattern = vim.g.colors_name})
