local c = require("nord.colours")
vim.api.nvim_create_augroup("nvim-code-action-menu-hl", {})
vim.api.nvim_create_autocmd("ColorScheme", {group = "nvim-code-action-menu-hl", pattern = "nord", callback = function()
	vim.api.nvim_set_hl(0, "CodeActionMenuMenuDisabled", {link = "NonText"})
	vim.api.nvim_set_hl(0, "CodeActionMenuMenuSelection", {link = "Visual"})
	vim.api.nvim_set_hl(0, "CodeActionMenuMenuIndex", {fg = c.comment})
	vim.api.nvim_set_hl(0, "CodeActionMenuDetailsPreferred", {fg = c.success})
	vim.api.nvim_set_hl(0, "CodeActionMenuDetailsDisabled", {fg = c.error})
	vim.api.nvim_set_hl(0, "CodeActionMenuDetailsAddedLinesCount", {fg = c.diff_add})
	vim.api.nvim_set_hl(0, "CodeActionMenuDetailsDeletedLinesCount", {fg = c.diff_delete})
	vim.api.nvim_set_hl(0, "CodeActionMenuDetailsAddedSquares", {link = "CodeActionMenuDetailsAddedLinesCount"})
	vim.api.nvim_set_hl(0, "CodeActionMenuDetailsDeletedSquares", {link = "CodeActionMenuDetailsDeletedLinesCount"})
	vim.api.nvim_set_hl(0, "CodeActionMenuDetailsAddedLine", {link = "CodeActionMenuDetailsAddedLinesCount"})
	vim.api.nvim_set_hl(0, "CodeActionMenuDetailsDeletedLine", {link = "CodeActionMenuDetailsDeletedLinesCount"})
	vim.api.nvim_set_hl(0, "CodeActionMenuDetailsCreatedFile", {fg = c.diff_add})
	vim.api.nvim_set_hl(0, "CodeActionMenuDetailsChangedFile", {fg = c.diff_text})
	vim.api.nvim_set_hl(0, "CodeActionMenuDetailsRenamedFile", {fg = c.diff_change})
	vim.api.nvim_set_hl(0, "CodeActionMenuDetailsDeletedFile", {fg = c.diff_delete})
end})
vim.api.nvim_exec_autocmds("ColorScheme", {group = "nvim-code-action-menu-hl", pattern = vim.g.colors_name})
